---
language: cpp
compiler: gcc
cache: ccache
dist: trusty
addons:
  apt:
    packages: libpulse-dev
  coverity_scan:
    project:
      name: "$TRAVIS_REPO_SLUG"
      description: Urho3D is a free lightweight, cross-platform 2D and 3D game engine
        implemented in C++ and released under the MIT license. Greatly inspired by
        OGRE and Horde3D.
    notification_email: urho3d.travis.ci@gmail.com
    build_command_prepend: rake cmake URHO3D_LUA=0 URHO3D_SAMPLES=1 URHO3D_TOOLS=1
      URHO3D_EXTRAS=1 URHO3D_DATABASE_SQLITE=1 URHO3D_LIB_TYPE=SHARED
    build_command: rake make numjobs=4
    branch_pattern: ".*Coverity-Scan$"
env:
  global:
  - secure: SLJCjkjDsTMbCIV9Wecz5JATnhk0fuzlnLMeZdvvFDv+8NL8cXyutkU0VfyRSLf3HSD1Js79a6fRMROyVGWj/w/BRrjqGnZzsB6+ZeJNnadiVIF5Gh+w90We5ccvSp2G4DyYgwkNnkKlJK7zNEWGu/K+bHL1EOCA+EIVrFMyA44=
  - secure: itgWNvH4Zj0hQpkUctVxMwJwVX3hIluVuvUbzO2XG7dxQaMMfcLGwVKgq8X1HOf4dJCUv5WL0jcSMWXbdc8tvqQJwBb5R2Z2JJYpTTAgtmLy7TNn6zgetZtGrYEJuTlxSItbS/NF4iPDO25ih7j5Ma0ffXRpBnlURQaytfYfFaQ=
  - LINUX=1
  - USE_CCACHE=1
  - CCACHE_SLOPPINESS=pch_defines,time_macros
  - CCACHE_COMPRESS=1
stage: scan
before_script:
- export TRAVIS_COMMIT=$TRAVIS_COMMIT~
- export COMMIT_MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
script: true
after_script: rake ci_delete_mirror
notifications:
  email:
    on_success: never
    on_failure: change
    recipients:
    - weitjong@gmail.com
